name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

  steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm i
        pm2 stop 0
        pm2 start 0
        pm2 save
